import { readFileSync } from "node:fs";
import packageInfo from "../package.json" with { type: "json" };

/** Generated by the dist build when the tree is clean and shipped with the
 * extension. An unbuilt or dirty checkout cannot claim a commit identity. */
function builtCommit(): string | null {
  try {
    const stamp: unknown = JSON.parse(
      readFileSync(new URL("./build-info.generated.json", import.meta.url), "utf8"),
    );
    if (stamp !== null && typeof stamp === "object" && "gitSha" in stamp) {
      if (stamp.gitSha === null) return null;
      if (typeof stamp.gitSha === "string" && /^[0-9a-f]{40}$/.test(stamp.gitSha)) {
        return stamp.gitSha;
      }
    }
    throw new Error("Invalid Shepy Pi build identity stamp");
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return null;
    throw error;
  }
}

export const extensionBuild: { pkgVersion: string; gitSha: string | null } = {
  pkgVersion: packageInfo.version,
  gitSha: builtCommit(),
};
